apiVersion: batch/v1
kind: Job
metadata:
  name: fampay-migrations
spec:
  template:
    spec:
      containers:
        - name: fampay
          image: hasher1705/fampay
          command: ['python', 'manage.py', 'migrate']
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: DB_HOST
              value: postgres-service

            - name: DB_NAME
              value: fampay_db

      restartPolicy: Never
  backoffLimit: 5
