# Generated by Django 3.2.5 on 2021-07-20 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('video_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('video_title', models.CharField(db_index=True, max_length=100)),
                ('video_description', models.TextField(db_index=True)),
                ('publishing_datetime', models.DateTimeField()),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThumbnailURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('resolution_type', models.CharField(choices=[('default', 'Default'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='default', max_length=10)),
                ('yt_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.youtubevideo')),
            ],
        ),
    ]
