# Generated by Django 3.2.5 on 2021-07-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_title',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
